### ISSUE TITLE
Named queries cause error when selected as display field on Splainer

### ISSUE THREAD

**Issue by nathancday** [o19s/solr-tmdb#19]
I think this type of syntax used to work for showing the score from a named query in Splainer:

```
f:$dateBoost
```

But now it will produce an errror. See this [link](http://splainer.io/#?solr=http:%2F%2Flocalhost:8983%2Fsolr%2Ftmdb%2Fselect%3FdebugQuery%3Don%26defType%3Dedismax%26qf%3Dtext_all%26indent%3Don%26q%3Dstar%20wars%26peopleQuery%3D%7B!field%20bf%3D''%20bq%3D''%20f%3Dtext_people%20mm%3D100%2525%20v%3D$q%7D%26dateBoost%3Drecip(ms(NOW,release_date),3.16e-11,10,1)%26bf%3Dif(query($peopleQuery),product($dateBoost,100),0)%26bf%3Dproduct($titleSearch,pow(vote_average,2))%26tie%3D1.0%26titleSearch%3D%7B!edismax%20bf%3D''%20pf%3Dtitle%20bq%3D''%20qf%3Dtitle%20mm%3D100%2525%20v%3D$q%7D%26fl%3Dtitle%20tagline%20text_people%20overview%20release_date%20vote_average%20vote_count&fieldSpec=title:title%20tagline%20text_people%20overview%20release_date%20vote_average%20vote_count%20f:$dateBoost).

If you remove the named query from the display field the error is gone. That means you lose the pretty name of the query and are left with the Lucene math syntax of it instead. See this [link](http://splainer.io/#?solr=http:%2F%2Fquepid-solr.dev.o19s.com:8985%2Fsolr%2Ftmdb%2Fselect%3Fq%3D*:*&fieldSpec=title:title%20tagline%20text_people%20overview%20release_date%20vote_average%20vote_count) for the working complement to query above.

This has been failing as a link test for a while now. I think we began to fix it, but not sure where that ended up.

**Comment by epugh** [comment]
This appears also related to https://github.com/o19s/quepid/issues/124

**Comment by epugh** [comment]
and maybe fixed in https://github.com/o19s/splainer-search/pull/88 ??   @worleydl thoughts on trying to get this fix deployed before Tuesday next week?

**Comment by worleydl** [comment]
Does this look right or is the name in the graph supposed to be dateBoost?
![image](https://user-images.githubusercontent.com/615271/95125342-d3e1b880-0722-11eb-8d0e-b18480b0bf0b.png)

**Comment by risdenk** [comment]
This worked well for what we did in training.
