### ISSUE TITLE
zip file for download does not contain the querqy libraries

### ISSUE THREAD

**Issue by david-fisher** [o19s/solr-tmdb#29]
Attempts to build using the docker.sh (or docker-compose up) produce an error:

dfisher@earthsea solr-tmdb-master % docker-compose up        
[+] Building 1.3s (8/8) FINISHED                                                
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 516B                                       0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for docker.io/library/solr:8.11.1             1.2s
 => [auth] library/solr:pull token for registry-1.docker.io                0.0s
 => [internal] load build context                                          0.0s
 => => transferring context: 2B                                            0.0s
 => CANCELED [1/3] FROM docker.io/library/solr:8.11.1@sha256:3a133043d41b  0.0s
 => => resolve docker.io/library/solr:8.11.1@sha256:3a133043d41bd2e5cbcba  0.0s
 => => sha256:3a133043d41bd2e5cbcba254c55a411b69dd253d5e2d8c8 549B / 549B  0.0s
 => => sha256:ad074897320306b910603f21996d0aea3e4174a0082 2.63kB / 2.63kB  0.0s
 => => sha256:5301008b13d28ce3eeb395e6b0e41662bcd1beb22 15.76kB / 15.76kB  0.0s
 => ERROR [2/3] COPY ./lib/querqy-solr-5.1.lucene810.0-jar-with-dependenc  0.0s
 => ERROR [3/3] COPY ./lib/querqy-regex-filter-1.1.0-SNAPSHOT.jar /opt/qu  0.0s
------
 > [2/3] COPY ./lib/querqy-solr-5.1.lucene810.0-jar-with-dependencies.jar /opt/querqy/lib/:
------
------
 > [3/3] COPY ./lib/querqy-regex-filter-1.1.0-SNAPSHOT.jar /opt/querqy/lib/:
------
failed to solve: failed to compute cache key: failed to walk /var/lib/docker/tmp/buildkit-mount347711749/lib: lstat /var/lib/docker/tmp/buildkit-mount347711749/lib: no such file or directory

**Comment by risdenk** [comment]
FYI @wrigleyDan  - This looks like it was introduced in PR #28

**Comment by david-fisher** [comment]
moving the lib folder with the jar files into the docker folder (where Dockerfile lives) resolves the issue. It is a relative path wrt to the build directory.

**Comment by wrigleyDan** [comment]
Thanks for catching that one and fixing it @david-fisher!
I somehow did not integrate the libs in PR https://github.com/o19s/solr-tmdb/pull/28 - no idea how that happened.
