### ISSUE TITLE
settings.cfg file missing

### ISSUE THREAD

**Issue by numb478** [o19s/solr-tmdb#3]
a configuration file referenced in the code is not found the repository.

file: 'ltr/train/indexMlTmdb.py '

code snippet

'config.read('settings.cfg')
--
44 | esUrl=config['DEFAULT']['ESHost']
45 | if len(argv) > 1:
46 | esUrl = argv[1]
'
is there any other config file which has all values required ?

**Comment by epugh** [comment]
@softwaredoug can you shed some light?   Is this one of those projects that for the LTR class we need to update?
